In [1]:
import pandas as pd
df = pd.read_csv("Multi-Class-Classification.csv")
df.head()

   Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [3]:
df.shape

(500, 4)

### Check for Missing values

In [4]:
df.isna().sum()

Gender    0
Height    0
Weight    0
Index     0
dtype: int64

### Label Encoding

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df.head()

   Gender  Height  Weight  Index
0       1     174      96      4
1       1     189      87      2
2       0     185     110      4
3       0     195     104      3
4       1     149      61      3

### Feature Scaling

In [6]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
df['Height'] = mm.fit_transform(df[['Height']])
df['Weight'] = mm.fit_transform(df[['Weight']])
df.head()

   Gender    Height    Weight  Index
0       1  0.576271  0.418182      4
1       1  0.830508  0.336364      2
2       0  0.762712  0.545455      4
3       0  0.932203  0.490909      3
4       1  0.152542  0.100000      3

### Train Test Split

In [13]:
x = df.iloc[:, 0:3]
y = df.iloc[:, 3]
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 1, shuffle = True)

### Build Model

### Logistic Regression

In [16]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(xtrain,ytrain)
print(LR.coef_,LR.intercept_)
print(LR.classes_)

[[-0.15374395  1.33270207 -2.34112665]
 [ 0.66297902  2.20037752 -3.20719227]
 [-0.40386676  0.81103027 -3.212253  ]
 [-0.14816064  0.76977    -0.77286699]
 [-0.13251339 -0.32840135  2.39746485]
 [ 0.17530572 -4.7854785   7.13597405]] [-1.13493297 -1.12357639  1.29063388  0.52276058  0.48349609 -0.03838119]
[0 1 2 3 4 5]