In [3]:
import pandas as pd
df = pd.read_csv('Social-Network.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

### Check for missing values

In [2]:
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

### Treating Categorical Variable

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

### Scaling Numerical Variable

In [6]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
df['EstimatedSalary'] = mm.fit_transform(df[['EstimatedSalary']])
df['Age'] = mm.fit_transform(df[['Age']])
df.head()

    User ID  Gender       Age  EstimatedSalary  Purchased
0  15624510       1  0.023810         0.029630          0
1  15810944       1  0.404762         0.037037          0
2  15668575       0  0.190476         0.207407          0
3  15603246       0  0.214286         0.311111          0
4  15804002       1  0.023810         0.451852          0

### Identify X and Y

In [7]:
x = df.iloc[:,1:4]
y = df.iloc[:,4]

### Split into Train and Test

In [9]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 1, shuffle = True)

# Building Model

### Logistic Regression

In [12]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(xtrain, ytrain)
print(LR.coef_, LR.intercept_)
print(LR.classes_)

[[0.02439599 5.14362337 2.88630661]] [-4.37015417]
[0 1]

### Evaluate Model

In [15]:
ypred = LR.predict(xtest)
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

print(confusion_matrix(ytest, ypred))

[[42  6]
 [ 8 24]]

In [16]:
print("Accuracy: ", accuracy_score(ytest, ypred))
print("Precision: ", precision_score(ytest, ypred))
print("Recall: ", recall_score(ytest, ypred))
print("F1_score: ", f1_score(ytest, ypred))
print("roc_auc_score: ", roc_auc_score(ytest, ypred))

Accuracy:  0.825
Precision:  0.8
Recall:  0.75
F1_score:  0.7741935483870968
roc_auc_score:  0.8125

### Probability Evaluation

In [17]:
LR.predict_proba(xtest)

array([[0.85277168, 0.14722832],
       [0.69314422, 0.30685578],
       [0.48480546, 0.51519454],
       [0.37432217, 0.62567783],
       [0.76643175, 0.23356825],
       [0.70094612, 0.29905388],
       [0.97530715, 0.02469285],
       [0.26253207, 0.73746793],
       [0.93640684, 0.06359316],
       [0.11689741, 0.88310259],
       [0.7671014 , 0.2328986 ],
       [0.63605902, 0.36394098],
       [0.73984298, 0.26015702],
       [0.14381629, 0.85618371],
       [0.20608922, 0.79391078],
       [0.0556801 , 0.9443199 ],
       [0.09520219, 0.90479781],
       [0.91086244, 0.08913756],
       [0.83287178, 0.16712822],
       [0.06550196, 0.93449804],
       [0.59702208, 0.40297792],
       [0.24795655, 0.75204345],
       [0.18768553, 0.81231447],
       [0.5487366 , 0.4512634 ],
       [0.69082148, 0.30917852],
       [0.96662554, 0.03337446],
       [0.22922431, 0.77077569],
       [0.32912424, 0.67087576],
       [0.42008619, 0.57991381],
       [0.12894083, 0.87105917],
       [0.76793457, 0.23206543],
       [0.94878297, 0.05121703],
       [0.94543078, 0.05456922],
       [0.15552792, 0.84447208],
       [0.85726114, 0.14273886],
       [0.81554459, 0.18445541],
       [0.97794144, 0.02205856],
       [0.75724416, 0.24275584],
       [0.58523534, 0.41476466],
       [0.98218065, 0.01781935],
       [0.12571141, 0.87428859],
       [0.08570681, 0.91429319],
       [0.56175254, 0.43824746],
       [0.93507752, 0.06492248],
       [0.21924039, 0.78075961],
       [0.64013157, 0.35986843],
       [0.56673358, 0.43326642],
       [0.21812269, 0.78187731],
       [0.60587829, 0.39412171],
       [0.42911262, 0.57088738],
       [0.93652991, 0.06347009],
       [0.76966828, 0.23033172],
       [0.51030795, 0.48969205],
       [0.65446751, 0.34553249],
       [0.5415296 , 0.4584704 ],
       [0.73854399, 0.26145601],
       [0.20179284, 0.79820716],
       [0.79417644, 0.20582356],
       [0.09630787, 0.90369213],
       [0.23989632, 0.76010368],
       [0.84042981, 0.15957019],
       [0.91095525, 0.08904475],
       [0.46181076, 0.53818924],
       [0.82345159, 0.17654841],
       [0.58550748, 0.41449252],
       [0.32319105, 0.67680895],
       [0.9508657 , 0.0491343 ],
       [0.56341616, 0.43658384],
       [0.22892836, 0.77107164],
       [0.76359805, 0.23640195],
       [0.3120158 , 0.6879842 ],
       [0.84133435, 0.15866565],
       [0.45650147, 0.54349853],
       [0.64029937, 0.35970063],
       [0.93082003, 0.06917997],
       [0.11639604, 0.88360396],
       [0.85364298, 0.14635702],
       [0.96592889, 0.03407111],
       [0.79196123, 0.20803877],
       [0.79019632, 0.20980368]])

In [18]:
LR.predict(xtest)

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0])

### Quick Evaluation of Accuracy Score

In [19]:
print('Training Accuracy: ', LR.score(xtrain, ytrain))
print('Test Accuracy: ',  LR.score(xtrain, ytrain))

Training Accuracy:  0.825
Test Accuracy:  0.825